### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [TheRaulXP/MMM-EMTValencia#1]
Can you add a screenshot directly to the repository? For example as `screenshot.png` or `example.png` in any folder :slightly_smiling_face: 

This would have the advantage that the image would be displayed in [the module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on.

**Comment by raulbalanza** [comment]
I have just uploaded one :)

**Comment by KristjanESPERANTO** [comment]
Thanks! Now your module looks nice in the list :slightly_smiling_face:
